name: Cool Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  cool-job:
    # The type of runner that the jobs will run on
    runs-on: macos-12
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # run the scripts before the main python thing
      - name: install dependencies
        run: |
          /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version


      # run the actual script that I care about
      - name: run python script
        run: echo "python3 main.py"
