name: Cool Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  cool job:
    # The type of runner that the jobs will run on
    runs-on: macos-12
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install dependencies
        run: |
          uname -m
          brew update
          brew install --cask google-chrome
          pip3 install -r requirements.txt

    runs-on: macos-12
    
      - name: run python script
        run: python3 main.py
